#! /bin/sh

### Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
polybar main &
picom &
dunst &
wal -R &
xidlehook --not-when-fullscreen --not-when-audio --timer 300 ${HOME}/.config/i3lock/lockscreen normal &

# Remove x cursor
xsetroot -cursor_name left_ptr &

### Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

### Source the Colors
. "${HOME}/.cache/wal/colors.sh"

### Window Styles
bspc config border_width         3
bspc config window_gap	         8 
bspc config normal_border_color "$color0"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color7"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Rules
bspc rule -a Pavucontrol state=floating
bspc rule -a kitty rectangle=420x200+585+385
