#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#f1f1f1cc'  # default
T='#FFFFFFFF'  # text
W='#ff00ffcc'  # wrong
V='#bb00bbbb'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--time-str="%H:%M:%S"  \
--date-str="%A, %m %Y" \
--verif-text="VERIFYING"	\
--wrong-text="WRONG!"	\
--radius 190		\
--ring-width 15.0	\
--time-size=60		\
--date-size=25		\
--layout-size=25		\
--verif-size=50		\
--wrong-size=50		\
--keylayout 1         \
