#!/bin/sh

### Source the Colors
. "${HOME}/.cache/wal/colors.sh"

B="$color0"    # blank
C="$color0"    # clear ish
D='#FFFFFFFF'  # default
T='#FFFFFFFF'  # text
W="$color1"    # wrong
V="$color2"    # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T       \
--wrong-color=$T       \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 1             \
--blur 5               \
--clock                \
--indicator            \
--time-str="%H:%M:%S"  \
--date-str="%A, %m %Y"  \
--verif-text="VERIFYING" \
--wrong-text="WRONG!"  \
--noinput-text="NO INPUT" \
--radius 200           \
--ring-width 10.0      \
--time-size=60         \
--date-size=25         \
--layout-size=25       \
--verif-size=50        \
--wrong-size=50        \
--keylayout 1          \
