# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Change "❯" color
[character]
success_symbol = "[❯](red)"

# Disable git modules
[git_branch]
disabled = true

[git_status]
disabled = true
